### ISSUE TITLE
To fix before launch

### ISSUE THREAD

**Issue by yitongzhang** [charliecf/web-patterns#14]
# Need to have
## Yitong
- [x] back button
- [x] About
- [x] Contact
- [x] Highlight Selected filter
- [x] Name, we need one.
- [x] Domain, we need one.
- [x] Side scroll triggered at 1400
- [x] About and Contact button are different from the normal styling

## Charlie
- [x] Remove CTA sub tags
- [x] Fuse customer and press into logos

# Nice to have
- [ ] Remove all filters in which there are less than 10 items
- [x] Footer bars not aligning if no pagination
- [ ] Add Pauline's website
- [ ] Human readable tag names
- [x] Reduce black line contrast

**Comment by charliecf** [comment]
@yitongzhang back button is done see commit `9f8ad01`, feel free to merge in the PR, I'm working on different branch now (branch : database)

**Comment by charliecf** [comment]
[Domain Names](https://devcenter.heroku.com/articles/custom-domains)

**Comment by charliecf** [comment]
deployed:
https://powerful-river-94324.herokuapp.com/
