### ISSUE TITLE
As a user, I want to filter the patterns so that I can focus on one element of my design at a time.

### ISSUE THREAD

**Issue by charliecf** [charliecf/web-patterns#2]
**Objective** - this feature is the fundamental aspect of this tool. As designers, you want to gather inspiration from other designs of a specific website element you're working on.

**User Stories** - designers like Yitong will go to this site for inspirations when mocking up and designing a certain functionality of a website

**Solution** - through the navigation sidebar on the left side of the website, when a user clicks on one of the categories. The images of the website should filter to only be populated and include the specific element that is filtered for.

**Functional Specs** - 
* when an element is selected, it should show some sort of indication that we're currently only looking at elements filtered with that specific tag. We'll be filtering based on labels.
* each image should have at least one label. labels to images is a many to one relationship as governed by the `tag` table. Labels can be created as listed in the `label` table. Each category should filter for at least one `tag` and then on the backend, only images associated to that certain tag should be populating the page.

**Comment by charliecf** [comment]
@yitongzhang can you help answer these product questions?

1. Can you select multiple tags to be filtered for? Ie. As a user, if I click on _Nav_ and then click on _Hero_, does the filters automatically apply to _Hero_ and deselect all _Nav_ selections? Or does it filter for _Nav_ AND _Hero_, or perhaps does it filter for _Nav_ OR _Hero_?

2. What is the visual change after a user selects a certain `tag`?

**Comment by yitongzhang** [comment]
> Can you select multiple tags to be filtered for?
For now, no. It's either or. The use case for wanting to see more than 1 type of thing is just so small that it's not worth adding 1 click (to uncheck) to the default action of changing sections.

> What is the visual change after a user selects a certain tag?
for label: opacity 0.5 → opacity 1, most likely
for displayed sections: probably old ones disappear → new ones appear. Even if there are sections that fit both the old and new label, they should disappear and reappear.

 Having a good animation for this feature is not MVP. Also, having everything move would probably be too gaudy. If we do need them eventually, I can do it in CSS.

**Comment by charliecf** [comment]
@yitongzhang I see that you have categories such as "Pricing" and underneath it has 'Simple' and 'Tiered'. How does that work and what is the user interaction with those categories?

Does user have the ability to click on entire categories or only sub categories?

In terms of content... ( see Issue #5 ), what's the minimum content we should have before launching the MVP?

**Comment by yitongzhang** [comment]
Both. Entire category = all sub categories selected

**Comment by charliecf** [comment]
In terms of the `section` table, the contents are as follows:
- name:string
- website:string
- file_location:string
- capture_date:date
- order:integer
