### ISSUE TITLE
Content for MVP

### ISSUE THREAD

**Issue by charliecf** [charliecf/web-patterns#5]
we should have at least 3 screenshots per label.

**Labels:**

- Nav
- Hero
- Features
- Social Proof
- Pricing
- CTA

Please put images labelled in /app/assets/images/content/{ID}.png

**Comment by yitongzhang** [comment]
Let's bump this to 10 per category. It's not gonna be very long. Maybe a few hours

**Comment by yitongzhang** [comment]
# Image format:

**Size**: 
1600px wide. 

**Name**: 
order-sitename-sectionname-instancenumber

e.g. 
`0-stripe-navbar-0` is the first element of the stripe site, a nav bar. There is only 1 navbar.
`2-stripe-feature-singlefeature-0` is the third element of the stripe site, a feature highlight. There is the first of its kind.
`2-stripe-feature-singlefeature-1` same as above, but the second of its kind.

**Comment by charliecf** [comment]
I think the naming doesn't need to be super intuitive as we scale, because everything will be stored via a table in the db. So imaging this at scale. It'll probably start becoming like 0001, 0002, etc.
